base_url = "https://tabi-community-skins.pages.dev"
title = "tabi community skins"
description = "A showcase of community-contributed skins for the tabi Zola theme. Browse, discover, and contribute your own custom color schemes."
author = "tabi community"
generate_feeds = true
compile_sass = true
minify_html = true
build_search_index = false

theme = "tabi"
default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[extra]
menu = [
    { name = "github", url = "https://github.com/welpo/tabi-community-skins", trailing_slash = false },
    { name = "contribute", url = "https://github.com/welpo/tabi-community-skins#contributing", trailing_slash = false },
    { name = "tabi theme", url = "https://welpo.github.io/tabi/", trailing_slash = false },
]

socials = [
    { name = "github", url = "https://github.com/welpo/tabi-community-skins", icon = "github" },
]

# Add a "copy" button to code blocks (loads ~700 bytes of JavaScript).
# Can be set at page or section levels, following the hierarchy: page > section > config. See: https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy
copy_button = true
